name = "Pascal"
grammar = "pascal"
path_suffixes = ["pas", "pp", "dpr", "dpk", "inc", "lpr"]
line_comments = ["// "]
block_comment = { start = "{", end = "}", prefix = "", tab_size = 1 }
autoclose_before = ";:.,=)]"
brackets = [
    { start = "(", end = ")", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
