[package]
name = "cargo_diagnostics"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/cargo_diagnostics.rs"
doctest = false

[dependencies]
anyhow.workspace = true
collections.workspace = true
lsp.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
